### ISSUE TITLE
Använd unless istället för istället för inverted if

### ISSUE THREAD

**Issue by alexdriaguine** [lw222gu/1dv450_lw222gu#1]
application_controller.rb, rad 22

Använd hellre unless istället för if!
raden kan ändras till 

``` ruby
unless current_user.admin?
```

**Comment by lw222gu** [comment]
Tack så mycket för alla bra kommentarer! Jag ska gå igenom dessa och fixa felen :-)

**Comment by lw222gu** [comment]
Fixat.

**Comment by 1dv450** [comment]
Bra kommentarer och bra fixat :)
