### ISSUE TITLE
många controller-metoder är inte RESTful

### ISSUE THREAD

**Issue by alexdriaguine** [lw222gu/1dv450_lw222gu#2]
Även om detta inte är ett API tycker jag man bör eftersträva att använda sig utav REST.

Detta görs lättas genom att använda :resources i routes.

routes.rb

``` ruby
resources :clients
```

Detta skapar RESful-routes.
Det går även ha nästlade resources

``` ruby
resources :clients do
    resources :apikeys
end

# Om du inte vill ha alla routes som medföljer så kan du specificera vilka du vill ha

resources :clients, only: [:index, :new, :create, :destroy]



# Du kan sedan namnge routes såhär

get      'signup'      =>   'clients#new'
```

**Comment by alexdriaguine** [comment]
Dålig namn på issues, tänkte lägga in den om session_controller här men den fick en egen. Denna handlar bara om routes

**Comment by lw222gu** [comment]
Fixat.
