### ISSUE TITLE
clients_controller.rb

### ISSUE THREAD

**Issue by alexdriaguine** [lw222gu/1dv450_lw222gu#5]
metoden delete skulle kunna ha en check ifall användaren är admin för att bestämma vilken path som ska redirectas till

``` ruby
def delete
  Client.find(params[:id]).destroy
  flash[:success] = "Appen raderades"
  if current_user.admin?
     redirect_to admin_path
  else
    redirect_to apikey_path
end
```

då ska du kunna ta bort user_delete och admin_delete metoderna.

**Comment by lw222gu** [comment]
Fixat.
