### ISSUE TITLE
onödig controller apikeys_controller.rb

### ISSUE THREAD

**Issue by alexdriaguine** [lw222gu/1dv450_lw222gu#9]
Metoden show i apikeys_controller.rb borde kunna läggas i clients_controller.rb istället.
Som jag fattat det från schema.rb så är Client-modellen en egenskap för api-nyckel, så det skulle vara bättre att lägga metoden i ClientController.

**Comment by lw222gu** [comment]
Tagit bort controllern apikeys och flyttat show till clients controllern.
